// GENERATED by scripts/gen_catalog.py — do not hand-edit.
// The shelves are the Shopify store: barcode, price and lot ledger come from
// the store, so every product here is one the recall chain can match and hold.
// Ingredients, allergens and most photos are Open Food Facts data for that
// barcode (ODbL, © Open Food Facts contributors); the rest of the photos are
// the maker's or a retailer's packshot (sources in scripts/gen_catalog.py).
//
// Whether a product is under recall is not recorded here. That is live: see
// features/recalls/useActiveRecalls.

export type Product = {
    gtin: string
    name: string
    brand: string
    size: string
    price: string
    /** empty when no photograph of this barcode exists */
    image: string
    imageSmall: string
    category: string
    allergens: string[]
    ingredients: string
    lots: string[]
}

export const CATALOG: Product[] = [
    {
        "gtin": "850073087008",
        "name": "Brown Butter Chocolate Chunk Cookie Dough",
        "brand": "Bakr",
        "size": "8 oz, 12 cookies",
        "price": "$4.99",
        "image": "https://images.openfoodfacts.org/images/products/085/007/308/7008/front_en.8.400.jpg",
        "imageSmall": "https://images.openfoodfacts.org/images/products/085/007/308/7008/front_en.8.200.jpg",
        "category": "baking",
        "allergens": [
            "eggs",
            "gluten",
            "milk"
        ],
        "ingredients": "wheat flour, brown cane sugar, chocolate chunks (cane sugar, unsweetened chocolate, cocoa butter), salted butter, egg, cane sugar, vanilla extract, baking soda, sea salt",
        "lots": [
            "2606022",
            "CLEAN-A",
            "CLEAN-B"
        ]
    },
    {
        "gtin": "4056489125846",
        "name": "Greek Style Shortbread Cookies with Apricot Filling",
        "brand": "Eridanous",
        "size": "330 g",
        "price": "$4.99",
        "image": "https://images.openfoodfacts.org/images/products/405/648/912/5846/front_de.12.400.jpg",
        "imageSmall": "https://images.openfoodfacts.org/images/products/405/648/912/5846/front_de.12.200.jpg",
        "category": "cookies",
        "allergens": [
            "gluten",
            "milk",
            "soybeans"
        ],
        "ingredients": "Farine de blé, 30% fourrage à l'abricot (14,7%² abricot, sucre, sirop de glucose-fructose, gélifiant: pectines; acidifiant: acide citrique; conservateur: sorbate de Fremstillet af:/Geproduceerd door:/Elaboré par:/Hergestellt von:/Prodotto da: Violanta SA, 6th km, GR-Trikala-Karditsa, potassium; arômes), margarine (BE: préparation de graisse végétale) Griekenland/Grèce/Griechenland/Grecia (huile de palme, huile de tournesol, eau, émulsifiant: mono - et For:/Voor:/Pour:/Für:/Prodotto per: Lidl Stiftung & Co. KG, diglycérides d'acides gras**; sel de cuisine), 15% glaçage à la noix de Stiftsbergstrasse 1, DE-74167 Neckarsulm, Duitsland/Allemagne/ coco (7,5% noix de coco hachée, huile de palme, sucre, lait entier Deutschland/Germania. en poudre, cacao en poudre, émulsifiant: lécithines (soja); arôme), sucre, 3% cuf***, jus d'orange à base de concentré, sirop de glucose, lait entier en poudre, poudres à lever: diphosphates, carbonate acide de sodium; arômes. 'Certifié Rainforest Alliance.",
        "lots": [
            "260315",
            "CLEAN-A",
            "CLEAN-B"
        ]
    },
    {
        "gtin": "860864000307",
        "name": "Power Play Fudge Ice Cream",
        "brand": "Gifford's",
        "size": "1 qt (946 mL)",
        "price": "$4.99",
        "image": "/products/860864000307.jpg",
        "imageSmall": "/products/860864000307-sm.jpg",
        "category": "ice-creams",
        "allergens": [
            "gluten",
            "milk",
            "peanuts",
            "soybeans"
        ],
        "ingredients": "Cream, sugar, milk fudge ripple (corn syrup, nonfat milk, high fructose corn syrup, hydrogenated vegetable oil (coconut, soybean), cocoa (processed with alkali), salt, xanthan gum, artificial flavor), corn syrup, broken cookies (sugar, wheat flour, vegetable shortening (partially hydrogenated soybean and/or cotton seed oil), cocoa (processed with alkali), degerminated yellow corn flour, invert sugar, corn starch, salt, vanilla, nonfat milk), fudge filled pucks (sugar, coconut oil, cocoa (processed with alkali), peanut oil, nonfat milk, whole milk, whey, salt, soy lecithin, natural flavors), nonfat dried milk, whey, dextrose, soy lecithin, guar gum, xanthan gum, carrageenan, yellow 5.",
        "lots": [
            "26184",
            "CLEAN-A",
            "CLEAN-B"
        ]
    },
    {
        "gtin": "085315054108",
        "name": "Sura Tanmen Hot & Sour Noodles & Soup Base",
        "brand": "Sun Noodle",
        "size": "15.4 oz (436 g)",
        "price": "$4.99",
        "image": "/products/085315054108.jpg",
        "imageSmall": "/products/085315054108-sm.jpg",
        "category": "noodles",
        "allergens": [],
        "ingredients": "",
        "lots": [
            "1226183",
            "CLEAN-A",
            "CLEAN-B"
        ]
    },
    {
        "gtin": "00175029",
        "name": "Imitation Crab Sticks",
        "brand": "Island Pacific",
        "size": "1 lb (454 g)",
        "price": "$4.99",
        "image": "/products/00175029.jpg",
        "imageSmall": "/products/00175029-sm.jpg",
        "category": "seafood",
        "allergens": [],
        "ingredients": "",
        "lots": [
            "2412292402HS",
            "CLEAN-A",
            "CLEAN-B"
        ]
    },
    {
        "gtin": "042272005833",
        "name": "Organic Lentil Soup, Light in Sodium",
        "brand": "Amy's",
        "size": "14.5 oz",
        "price": "$4.99",
        "image": "https://images.openfoodfacts.org/images/products/004/227/200/5833/front_en.48.400.jpg",
        "imageSmall": "https://images.openfoodfacts.org/images/products/004/227/200/5833/front_en.48.200.jpg",
        "category": "soups",
        "allergens": [
            "celery"
        ],
        "ingredients": "Filtered water, organic green lentils, organic celery, organic carrots, organic onions, organic potatoes, organic extra virgin olive oil, sea salt, organic spices.",
        "lots": [
            "60D0924",
            "CLEAN-A",
            "CLEAN-B"
        ]
    },
    {
        "gtin": "858792003323",
        "name": "Super Skin Dietary Supplement",
        "brand": "Mellish Island",
        "size": "60 capsules",
        "price": "$4.99",
        "image": "/products/858792003323.jpg",
        "imageSmall": "/products/858792003323-sm.jpg",
        "category": "supplements",
        "allergens": [],
        "ingredients": "",
        "lots": [
            "CA1G24",
            "CLEAN-A",
            "CLEAN-B"
        ]
    },
    {
        "gtin": "100000010150",
        "name": "Burger Chicken Fillet",
        "brand": "Fresh to You",
        "size": "5 oz",
        "price": "$4.99",
        "image": "",
        "imageSmall": "",
        "category": "poultry",
        "allergens": [],
        "ingredients": "",
        "lots": [
            "26171",
            "CLEAN-A",
            "CLEAN-B"
        ]
    }
]

export function findProduct(gtin: string): Product | undefined {
    const g = gtin.replace(/^0+/, '')
    return CATALOG.find((p) => p.gtin.replace(/^0+/, '') === g)
}
